apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-information
  namespace: weavek8sops
spec:
  encryptedData:
    password: AgALA6dj14ExDBIFrIuLidVGpYYZV7Xj43LCv7zjOxwewoGbtG++IkELIH4dVlnpF3Pq/BSYvJ34nj/r+X5OIEJrDQxzl09+tZ2QrXyaWIiitgCrqglmt3tAcROAJQxkTHKusVJMqXHqeuL0WuFiiONQdZWPQUhYoPVRryoHOw9XH58BwfqNMZhYtyNZ3Q7RVwfxmRwtmjz8+6/Tzl4xmEKf9i1L0KdYoqVeTspdpHJBuI8pUGQGheIQrP+J6KJrLJWfddB1KgmtsZ/BOC6TDko/tolAPABS6u7htlrHoDTWN5URMXo0P7W5D8FrKc5iJtEDv1wM6MqEpnFROttElp8TIsMi/fTGxeQ3SoiCbjzKWfd0P+yQjQGQ7cXzbr6A0BlBtAvimvv99qVdIxZOzb0nP04UPs/PAz3b7bKO2rpBNOfMTUrGVG6uYo7ymDizQrTXb4Rd33fxBkk6D0gJ5oKe6QiSkpKdC+0OAAkUzwC5D/2+cOxkLNhV72NKcmA0pQ1OkDWjuJXiiGZwiDDGPNNsPDR/LL2fOXEAkcJr3tQ1f2JSqrslVIiaMJ+q4YL5l1e0+Tn/z1hV13oFekCiqgubOMOYwlGo60zh6BY0YaYFcezWKkPq/cBtIYFZxJFgsFl56CIzCHcCaE/TsHEHVyRTZmn/IC7LnkifDD5M0vRM3sjZlGXarDp0qwEwvMzAxRj384ggHInk5bo=
    username: AgAlJT/RUYfNjqK1nsedUHL2k/B5GwozTGZmNkG1sMQb2l5an1QQ31byA1ZLW7NwYuMH16WYdsMb5txfz+aLg7jeOFt+ZhE6nhM0yKDbpH196FNKnHCTjFFlLtWxwwyuhwEV9pdfG0QOVihnRNQT1qM2j8Bzd4eeqxybDmxXjcWbBCDAUZ0cPKarAn7N5VJhEFJwMF97OGTx3IFcWpvI0+7Qc8P1ngczcz8cHRcmRBppzVmqoLVL8vC7IPrg3Br/l3AI464BeQ6OMN2yWopCN9RDhnaHG2wHRmKEmUuVtwn7usKeGQaH5FkrnXK/5yNhGpU2mS+MVBdmUFdnRPescAEH8jQlQtVgwCDGbTTFqK4YKtgYSBpKJ6A4kJNsiQTqF+tWGaYl4DCQtGZdAkK+JkvnlYmKgHofSQJdzsfqw+9pwjFO0WfbFpMNzsWPeLXgHuKyaXFp525+GPEndh0vpuJG8b7SI8aZXKENELgVnf7k+97SIbS+I8WSWKB5PfyM6jzby9ZDHAd4XTNjrQYuzzy/NrchT/blqUtGvD9dK3pSn7RiWgYbKK2ekcvw0LmJcIQEj2MZEQBQv38A+9Z18XMY2/4+a3VXmiaTJXQ030nsvK847jDQkXZr31A4OU5yVGPJ+XoOlZu6oOLAjSDv7EgSVmiOxvf8gwst8W8PEL+TFFsg2jSu9vgpWON045CUTA2o9glETfO4wyw=
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-information
      namespace: weavek8sops
    type: Opaque
status: {}

